- id: '1649267960272'
  alias: System Shutdown Notification
  description: Send notification on Home Assistant stop
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.telegram_chat_id_swart_ninja_smart_home_group
    data:
      message: 👋 Home Assistant is shutting down... Bye!
  mode: single
- id: '1649268089255'
  alias: System Start Notification
  description: Send notification on Home Assistant start
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.telegram_chat_id_swart_ninja_smart_home_group
    data:
      message: 🥳 Home Assistant is starting up again.
  mode: single
- id: '1649357383872'
  alias: 'Office Light On: Motion'
  description: Turn on a light, based on motion detection, and low light level.
  use_blueprint:
    path: swartninja/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.office_motion
      target_entity: light.office_ceiling
      illuminance_sensor: sensor.office_zw100_multisensor_luminance
      illuminance_cutoff: input_number.office_light_on_motion_automation_illuminance_cutoff
      blocker_entity: input_boolean.house_mode_away
      no_motion_wait: input_number.office_light_on_motion_automation_no_motion_wait
      target_off_entity: []
- id: '1649365144329'
  alias: 'Hall Light On: Motion'
  description: Turn on a light, based on motion detection, and low light level.
  use_blueprint:
    path: swartninja/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.hall_motion
      target_entity: script.hall_lights_on_dimmed_or_full
      illuminance_sensor: sensor.hall_multisensor_luminance
      illuminance_cutoff: input_number.hall_light_on_motion_automation_illuminance_cutoff
      blocker_entity: input_boolean.house_mode_away
      no_motion_wait: input_number.hall_light_on_motion_automation_no_motion_wait
      target_off_entity:
      - light.hall_zw111_nano_dimmer
- id: '1649366156716'
  alias: 'Bathroom Light On: Motion'
  description: Turn on a light, based on motion detection, and low light level.
  use_blueprint:
    path: swartninja/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.bathroom_motion
      target_entity: script.bathroom_lights_on_dimmed_or_full
      illuminance_sensor: sensor.bathroom_multisensor_luminance
      illuminance_cutoff: input_number.bathroom_light_on_motion_automation_illuminance_cutoff
      blocker_entity: input_boolean.house_mode_away
      no_motion_wait: input_number.bathroom_light_on_motion_automation_no_motion_wait
      target_off_entity:
      - light.bathroom_zw111_nano_dimmer
- id: '1649376556972'
  alias: 'Man Cave Light On: Motion'
  description: Turn on a light, based on motion detection, and low light level.
  use_blueprint:
    path: swartninja/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.man_cave_motion
      target_entity: light.man_cave_ceiling
      illuminance_sensor: sensor.man_cave_multisensor_luminance
      illuminance_cutoff: input_number.man_cave_light_on_motion_automation_illuminance_cutoff
      blocker_entity: binary_sensor.man_cave_light_automation_blocking_entity
      no_motion_wait: input_number.man_cave_light_on_motion_automation_no_motion_wait
      turn_off_blocker_entity: binary_sensor.panasonic_tv
- id: '1649491949914'
  alias: 'Living Room Light On: Motion'
  description: Turn on a light, based on motion detection, and low light level.
  use_blueprint:
    path: swartninja/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.living_room_motion
      target_entity: script.living_room_lights_on_main_or_secondary
      illuminance_sensor: sensor.living_room_luminance
      illuminance_cutoff: input_number.living_room_light_on_motion_automation_illuminance_cutoff
      blocker_entity: binary_sensor.living_room_light_automation_blocking_entity
      no_motion_wait: input_number.living_room_light_on_motion_automation_no_motion_wait
      turn_off_blocker_entity: media_player.living_room_television
      target_off_entity:
      - light.living_room_mood
      - light.living_room_ceiling
- id: '1649529348038'
  alias: 'Kitchen Light On: Motion'
  description: Turn on a light, based on motion detection, and low light level.
  use_blueprint:
    path: swartninja/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.kitchen_motion
      target_entity: script.kitchen_lights_on_main_or_secondary
      illuminance_sensor: sensor.kitchen_multisensor_luminance
      illuminance_cutoff: input_number.kitchen_light_on_motion_automation_illuminance_cutoff
      blocker_entity: input_boolean.house_mode_away
      no_motion_wait: input_number.kitchen_light_on_motion_automation_no_motion_wait
      turn_off_blocker_entity: media_player.kitchen_apple_tv
      target_off_entity:
      - light.kitchen_ceiling
      - light.kitchen_side
- id: '1649530119015'
  alias: Kitchen Cupboard LED's
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
  - platform: state
    entity_id: light.kitchen_ceiling
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: state
        entity_id: light.kitchen_ceiling
        state: 'off'
      sequence:
      - service: light.turn_on
        data:
          transition: 10
          brightness_pct: 50
        target:
          entity_id: light.kitchen_cupboard
    default:
    - service: light.turn_off
      data:
        transition: 10
      target:
        entity_id: light.kitchen_cupboard
  mode: single
- id: '1649540903378'
  alias: .Automation Test
  description: ''
  trigger:
  - platform: template
    value_template: '{{ is_state(''binary_sensor.office_motion'', ''off'') }}'
    for:
      minutes: '{{ states[no_motion_wait].state | int(0) }}'
  condition:
  - condition: state
    entity_id: automation.bathroom_light
    for:
      hours: 0
      minutes: 0
      seconds: 0
    state: 'on'
  action:
  - service: notify.mobile_app_dick_iphone
    data:
      message: Test Office No Motion
  trigger_variables:
    no_motion_wait: input_number.office_light_automation_turn_off_wait_time
  variables:
    target_entity: script.kitchen_lights_on_main_or_secondary
    illuminance_currently: sensor.kitchen_multisensor_luminance
    illuminance_cutoff: input_number.kitchen_light_automation_illuminance_cutoff
    blocker_entity: input_boolean.house_mode_away
    time_limit_before:
    time_limit_after:
    entity_domain: '{{ states[target_entity].domain }}'
    turn_off_blocker_entity: media_player.kitchen_apple_tv
    target_off_entity: script.kitchen_lights_off
  mode: restart
  max_exceeded: silent
- id: '1649558220358'
  alias: .BluePrint Test
  description: ''
  use_blueprint:
    path: swartninja/lights_off_no_motion.yaml
    input:
      motion_entity: binary_sensor.office_motion
      automation_entity: automation.office_light_on_motion
      light_target:
        entity_id:
        - light.office_ceiling
        - light.office_shelf
      no_motion_wait: input_number.office_light_automation_turn_off_wait_time
- id: '1649647741261'
  alias: Office Light Off
  description: ''
  use_blueprint:
    path: swartninja/auto_light_off.yaml
    input:
      trigger_entity: binary_sensor.office_light_off_automation_trigger_entity
      target_off_entities:
      - light.office_ceiling
      - light.office_shelf
      automation_entity: automation.office_light_on_motion
      blocker_entity: input_boolean.house_mode_away
- id: '1649703754954'
  alias: 'Hall Light On: Front Door Open'
  description: Turn on hall light if it is dark and the front door opens
  trigger:
  - platform: state
    entity_id: binary_sensor.hall_multisensor_door
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ (states(''sensor.hall_multisensor_luminance'') | int(0) <
      states(''input_number.hall_light_on_motion_automation_illuminance_cutoff'')
      | int(0)) and is_state(''light.hall_zw111_nano_dimmer'', ''off'') }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id: light.hall_zw111_nano_dimmer
  - delay:
      minutes: '{{ states(''input_number.hall_light_on_motion_automation_no_motion_wait'')
        | int(0) }}'
  - wait_template: '{{ is_state(''binary_sensor.hall_motion'', ''off'') }}'
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.hall_zw111_nano_dimmer
  mode: single
- id: '1649738077769'
  alias: 'Front Door Light On: Motion'
  description: ''
  use_blueprint:
    path: swartninja/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.fdc_motion
      target_entity: light.front_door_ceiling
      blocker_entity: binary_sensor.front_door_light_on_motion_automation_blocking_entity
      no_motion_wait: input_number.front_door_light_on_motion_automation_no_motion_wait
- id: '1649811322196'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: swartninja/update_notifications.yaml
    input:
      reminder_hours: '1'
      update_entities:
      - update.home_assistant_supervisor_update
      - update.home_assistant_core_update
      - update.atomic_calendar_revive_update
      - update.alexa_media_player_update
      - update.auto_entities_update
      - update.bar_card_update
      - update.browser_mod_update
      - update.button_card_update
      - update.card_mod_update
      - update.card_tools_update
      - update.fold_entity_row_update
      - update.glances_update
      - update.chrony_update
      - update.cover_control_button_row_update
      - update.home_assistant_google_drive_backup_update
      - update.ics_update
      - update.home_assistant_operating_system_update
      - update.influxdb_update
      - update.layout_card_update
      - update.living_room_curtains_firmware
      - update.hacs_update
      - update.ftp_update
      - update.mariadb_update
      - update.mini_graph_card_update
      - update.monitor_docker_update
      - update.mini_media_player_update
      - update.node_red_companion_update
      - update.samba_share_update
      - update.mosquitto_broker_update
      - update.node_red_update
      - update.simple_thermostat_update
      - update.esphome_update
      - update.state_switch_update
      - update.echonetlite_platform_update
      - update.studio_code_server_update
      - update.sun_card_update
      - update.swart_ninja_dark_theme_update
      - update.swartninjanas_dsm_update
      - update.dining_room_sml_window_firmware
      - update.deepstack_object_custom_integration_update
      - update.dining_room_corner_window_firmware
      - update.weather_card_update
      - update.z_wave_js_update
      - update.vertical_stack_in_card_update
      - update.uptime_card_update
      - update.terminal_ssh_update
      - update.template_entity_row_update
      mobile_app_device: 53b65c3460f56fbb2eb507ff241c47e4
      send_to_ha: true
      run_config_check: true
- id: '1649837563554'
  alias: 'Phone Charger On: Battery Low'
  description: ''
  use_blueprint:
    path: swartninja/phone_charger.yaml
    input:
      switch: switch.d1mini_4_channel_relay_03
      phone_battery: sensor.dick_iphone_battery_level
      person_home: person.dick
      discharged_percent: 30
- id: '1649841335537'
  alias: Man Cave Light Off
  description: ''
  use_blueprint:
    path: swartninja/auto_light_off.yaml
    input:
      trigger_entity: binary_sensor.man_cave_light_off_automation_trigger_entity
      automation_entity: automation.man_cave_light_on_motion
      blocker_entity: input_boolean.house_mode_away
      target_off_entities:
      - light.man_cave_ceiling
      - light.man_cave_kitchen_2gang_switch_one
      - light.man_cave_kitchen_3gang_switch_two
- id: '1649873592073'
  alias: Man Cave Bathroom Light Off
  description: Turn off the light after 15min if it is day or 1hour if it is night
  trigger:
  - platform: state
    entity_id: light.man_cave_bathroom_ceiling
    to: 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: sun
        after: sunrise
        before: sunset
      sequence:
      - delay:
          hours: 0
          minutes: 45
          seconds: 0
          milliseconds: 0
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.man_cave_bathroom_ceiling
    default:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.man_cave_bathroom_ceiling
  mode: single
