---
##############################################################################################
# Lovelace
# Zones allow you to specify certain regions on earth (for now).
#
# URL: https://www.home-assistant.io/integrations/zone/
##############################################################################################

custom_header:
  compact_mode: true
  button_text:
    options: "{{ hours24 }}:{{ minutesLZ }}"

button_card_templates:
  motion_sensor_btn:
    color_type: card
    name: Motion
    show_state: true
    layout: name_state
    styles:
      card:
        - background: transparent
        - box-shadow: none
      icon:
        - color: var(--dark-primary-color)
    state:
      - value: "on"
        icon: mdi:motion-sensor
        styles:
          icon:
            - color: var(--accent-color)
          name:
            - color: var(--primary-text-color)
      - operator: default
        icon: mdi:walk
        styles:
          icon:
            - color: var(--dark-primary-color)
  door_sensor_btn:
    color_type: card
    name: Door
    show_state: true
    layout: name_state
    styles:
      card:
        - background: none
        - box-shadow: none
      icon:
        - color: var(--dark-primary-color)
    state:
      - value: "on"
        icon: mdi:door-open
        styles:
          icon:
            - color: var(--accent-color)
          name:
            - color: var(--primary-text-color)
      - operator: default
        icon: mdi:door-closed
        styles:
          icon:
            - color: var(--dark-primary-color)
  alt_buttons:
    styles:
      card:
        - background-color: var(--secondary-color)
        - box-sizing: border-box
  header_button:
    styles:
      card:
        - padding: 5px 15px
        - border: 2px solid var(--primary-color);
        - background: red
        - box-shadow: none
      name:
        - color: var(--primary-text-color)
        - justify-self: start
        - font-size: var(--ha-card-header-font-size, 24px)
        - letter-spacing: -0.012em;
        - font-family: var(--ha-card-header-font-family, inherit)

title: SNSH
background: var(--background-image)
views:
  - !include lovelace/views/dashboard_view.yaml
  - !include lovelace/views/living_room_view.yaml
  - !include lovelace/views/man_cave_view.yaml
  - !include lovelace/views/office_view.yaml
  - !include lovelace/views/hall_view.yaml
  # - !include lovelace/views/bathroom_view.yaml
  # - !include lovelace/views/dining_room_view.yaml
  # - !include lovelace/views/kitchen_view.yaml
  - !include lovelace/views/master_bedroom_view.yaml
  - !include lovelace/views/nico_bedroom_view.yaml
  - !include lovelace/views/max_bedroom_view.yaml
