---
id: a0a642be-3b1c-4582-9032-b9b481c78cfd
alias: "System Updater Notification: HACS"
description: Create a notification when there is updates pending in HACS
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.updater_hacs
    from: "off"
    to: "on"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: binary_sensor.updater_hacs
    state: "on"
action:
  - service: persistent_notification.create
    data_template:
      title: 🆕 Updates pending in HACS
      message: >-
        {% for repo in state_attr('sensor.hacs', 'repositories') %}
          ** {{ repo.display_name }}: _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
        {% endfor %}
  - service: notify.telegram_chat_id_swart_ninja_smart_home_group
    data_template:
      title: 🆕 Updates pending in HACS
      message: >-
        {% for repo in state_attr('sensor.hacs', 'repositories') %}
          ** {{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
        {% endfor %}
