---
esphome:
  name: ${node_name}
  comment: "Sonoff Basic. (ID: ${node_id})"
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2
  build_path: ./build/${node_name}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - <<: !include sensor/uptime.config.yaml
  - <<: !include sensor/wifi_signal.config.yaml

binary_sensor:
  - <<: !include binary_sensor/connection_status.config.yaml
  # Wires soldered to the sonoff basic
  - platform: gpio
    id: button_gpio_14
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_state:
      then:
        - switch.toggle: switch_relay

  # Button on the Sonoff Basic
  - platform: gpio
    id: button_gpio_0
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_click:
      min_length: 1s
      max_length: 10s
      then:
        - switch.toggle: switch_restart
    on_press:
      - switch.toggle: switch_relay

text_sensor:
  - <<: !include text_sensor/version.config.yaml

switch:
  - platform: restart
    name: ${device_verbose_name} Restart
    id: switch_restart
  - platform: gpio
    icon: ${switch_icon}
    name: ${device_verbose_name}
    pin: GPIO12
    id: switch_relay

status_led:
  pin:
    number: GPIO13
    inverted: true
