---
esphome:
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/${node_name}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable Webserver
web_server:
  port: 80
  css_url: http://192.168.1.211:8123/local/esphome/webserver-v1.min.css
  js_url: http://192.168.1.211:8123/local/esphome/webserver-v1.min.js

binary_sensor:
  - <<: !include binary_sensor/connection_status.config.yaml

text_sensor:
  - <<: !include text_sensor/version.config.yaml
  - <<: !include text_sensor/wifi_info.config.yaml

sensor:
  - <<: !include sensor/uptime.config.yaml
  - <<: !include sensor/wifi_signal.config.yaml

switch:
  - platform: restart
    name: ${device_verbose_name} Restart
    id: switch_restart

status_led:
  pin:
    number: GPIO2
    inverted: true
