---
substitutions:
  node_id: 22FCC1
  node_name: frontdoor-ceiling
  device_verbose_name: Front Door Ceiling

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/shelly_1_base.yaml
