---
substitutions:
  node_id: 17FEDB
  node_name: kitchen-side
  device_verbose_name: Kitchen Side
  switch_icon: mdi:light-switch

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/sonoff_basic_base.yaml
