---
substitutions:
  node_id: "4C86CF"
  node_name: kitchen-motion-led
  device_verbose_name: Kitchen Motion LED

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/nodemcu_base.yaml

binary_sensor:
  - platform: gpio
    pin: D2
    name: ${device_verbose_name} Motion
    device_class: motion

light:
  - platform: monochromatic
    name: Kitchen Cupboard
    output: output_led_light

output:
  - platform: esp8266_pwm
    id: output_led_light
    pin: D1
