---
substitutions:
  node_id: 17FEDB
  node_name: kitchen_side
  device_verbose_name: Kitchen Side
  switch_icon: mdi:track-light

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
