---
  # Top Button
  #   - Tripple:  Restart
  #   - Double:   Send event (BTN_TOP_DOUBLE)
  #   - Long:     Send event (BTN_TOP_LONG)
  #   - Single:   Toggle Relay 1
  # Bottom Button
  #   - Double:   Send event (BTN_BOTTOM_DOUBLE)
  #   - Long:     Send event (BTN_BOTTOM_LONG)
  #   - Single:   Send event (BTN_BOTTOM_SINGLE) or Toggle Relay 2, if API not available
  
  # Available Outputs
  # - relay01
  # - relay02

substitutions:
  node_name: living-room-2gang-switch
  node_id: 92E4B9
  device_verbose_name: Living Room 2Gang Switch

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/zemismart_ks811_2gang_basic.yaml

binary_sensor:
  # Top
  - platform: gpio
    id: button_top
    pin:
      number: GPIO16
      mode: INPUT
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Tripple Clicked"
          - switch.toggle: switch_restart
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_TOP_DOUBLE
      - timing:
          - ON for at least 1.1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_TOP_LONG
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - light.toggle: light_top
  # Bottom
  - platform: gpio
    id: button_bottom
    pin:
      number: GPIO5
      mode: INPUT
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_BOTTOM_DOUBLE
      - timing:
          - ON for at least 1.1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_BOTTOM_LONG
      - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - light.toggle: light_bottom

light:
  - platform: binary
    name: ${device_verbose_name} One
    output: relay01
    id: light_top
  - platform: binary
    name: ${device_verbose_name} Two
    output: relay02
    id: light_bottom
    restore_mode: ALWAYS_ON

