---
# Top Button
#   - Tripple:  Restart
#   - Double:   Send event (BTN_TOP_DOUBLE)
#   - Long:     Send event (BTN_TOP_LONG)
#   - Single:   Toggle Relay 1
# Middle Button
#   - Double:   Send event (BTN_MIDDLE_DOUBLE)
#   - Long:     Send event (BTN_MIDDLE_LONG)
#   - Single:   Toggle Mood Light or or Toggle Relay 2, if API not available
# Bottom Button
#   - Double:   Open Living Room Curtains
#   - Long:     Close Living Room Curtains
#   - Single:   Stop Living Room Curtains or Toggle Relay 3, if API not available

# Available Outputs
# - relay01
# - relay02
# - relay03

substitutions:
  node_name: living_room_3gang_switch
  node_id: "721BEC"
  device_verbose_name: Living Room 3Gang Switch

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/zemismart_ks811_3gang_basic.yaml

binary_sensor:
  # Top
  - platform: gpio
    id: button_top
    pin:
      number: GPIO16
      mode: INPUT
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Tripple Clicked"
          - switch.toggle: switch_restart
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_TOP_DOUBLE
      - timing:
          - ON for at least 1.1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_TOP_LONG
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - light.toggle: light_top
  # Middle
  - platform: gpio
    id: button_middle
    pin:
      number: GPIO5
      mode: INPUT
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_MIDDLE_DOUBLE
      - timing:
          - ON for at least 1.1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_MIDDLE_LONG
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          # Toggle Mood Light
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: light.living_room_mood
          - switch.toggle: switch_relay02
  # Bottom
  - platform: gpio
    id: button_bottom
    pin:
      number: GPIO4
      mode: INPUT
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - if:
              condition:
                api.connected:
              then:
                # Open Living Room Curtains
                - homeassistant.service:
                    service: cover.open_cover
                    data:
                      entity_id: cover.living_room_sliding_door_curtain
      - timing:
          - ON for at least 1.1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - if:
              condition:
                api.connected:
              then:
                # Close Living Room Curtains
                - homeassistant.service:
                    service: cover.close_cover
                    data:
                      entity_id: cover.living_room_sliding_door_curtain
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          # Stop Living Room Curtains
          - homeassistant.service:
              service: cover.stop_cover
              data:
                entity_id: cover.living_room_sliding_door_curtain
          - switch.toggle: switch_relay03

light:
  - platform: binary
    name: Living Room Ceiling
    output: relay01
    id: light_top

switch:
  - platform: output
    id: switch_relay02
    output: relay02
  - platform: output
    id: switch_relay03
    output: relay03
