---
# Top Button
#   - Tripple:  Restart
#   - Double:   Send event (BTN_TOP_DOUBLE)
#   - Long:     Send event (BTN_TOP_LONG)
#   - Single:   Toggle Relay 1
# Middle Button
#   - Double:   Send event (BTN_MIDDLE_DOUBLE)
#   - Long:     Send event (BTN_MIDDLE_LONG)
#   - Single:   Toggle Relay 2
# Bottom Button
#   - Double:   Send event (BTN_BOTTOM_DOUBLE)
#   - Long:     Send event (BTN_BOTTOM_LONG)
#   - Single:   Toggle Relay 3

# Available Outputs
# - relay01
# - relay02
# - relay03

substitutions:
  node_name: man_cave_kitchen_3gang_switch
  node_id: FDA939
  device_verbose_name: Man Cave Kitchen 3Gang Switch

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/zemismart_ks811_3gang_basic.yaml

web_server:
  port: 80

binary_sensor:
  # Top
  - platform: gpio
    id: button_top
    pin:
      number: GPIO16
      mode: INPUT
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Tripple Clicked"
          - switch.toggle: switch_restart
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_TOP_DOUBLE
      - timing:
          - ON for at least 1.1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_TOP_LONG
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          # - light.toggle: light_top
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.man_cave_kitchen_2gang_switch_one
              else:
                - logger.log: "Not connected to API!"
                - switch.toggle: switch_relay01
  # Middle
  - platform: gpio
    id: button_middle
    pin:
      number: GPIO5
      mode: INPUT
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_MIDDLE_DOUBLE
      - timing:
          - ON for at least 1.1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_MIDDLE_LONG
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - light.toggle: light_middle
  # Bottom
  - platform: gpio
    id: button_bottom
    pin:
      number: GPIO4
      mode: INPUT
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_BOTTOM_DOUBLE
      - timing:
          - ON for at least 1.1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.event:
                    event: esphome.${node_name}
                    data:
                      data: BTN_BOTTOM_LONG
      - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.man_cave_ceiling
              else:
                - logger.log: "Not connected to API!"
                - switch.toggle: switch_relay03

light:
  - platform: binary
    name: ${device_verbose_name} Two
    output: relay02
    id: light_middle

switch:
  - platform: output
    # name: ${device_verbose_name} One
    id: switch_relay01
    output: relay01
  - platform: output
    # name: ${device_verbose_name} Three
    id: switch_relay03
    output: relay03