---
substitutions:
  node_id: 22F3C2
  node_name: shelly1_22f3c2
  device_verbose_name: Shelly 1 22F3C2

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/shelly_1_base.yaml
