---
substitutions:
  node_id: 0FBC52
  node_name: sonoff_basic_0fbc52
  device_verbose_name: Sonoff Basic 0FBC52
  switch_icon: mdi:light-switch

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
