---
substitutions:
  node_id: 0F6E67
  node_name: sonoff_basic_0f6e67
  device_verbose_name: Sonoff Basic 0F6E67
  switch_icon: mdi:light-switch

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
