---
substitutions:
  node_id: 22F3C2
  node_name: stairs-ceiling
  device_verbose_name: Stairs Ceiling

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/shelly_1_base.yaml
