---
##################################################################################################################
# Sensor
# Home Assistant currently supports a wide range of sensors.
#
# URL: https://www.home-assistant.io/integrations/sensor/
##################################################################################################################
sensor: !include_dir_list ../entities/sensors
